---
output:
  rmarkdown::github_document:
    html_preview: no
fontsize: 11pt
documentclass: article
---

# Comparison with other SDM packages

Isn’t this just another SDM package? Indeed it is, but \pkg{ibis.iSDM} has
particular features that allow greater flexibility in how models are
created and run than other packages. It is less about reinventing the wheel, but rather bringing strengths from different tools together.

*Non exhaustive list acknowledging other SDM packages in R:*

-   [hSDM](https://github.com/ghislainv/hSDM) -&gt; Bayesian framework
    for mixed models. Fast, but little flexibility with regards to
    weights or offsets.
-   [multispeciesPP](https://github.com/wfithian/multispeciesPP) -&gt;
    Package that allows integrated SDMs, however it has not been further 
    developed since years and key gaps remain.
-   [inlabru](https://github.com/inlabru-org/inlabru) -&gt; Package
    specifically for LGCP with INLA, now integrated as engine in _ibis.iSDM_
-   [pointedSDMs](https://github.com/oharar/PointedSDMs) -&gt; Another wrapper for INLA
    that allows to integrate different datasets in a SDM.
-   [biomod2](https://github.com/biomodhub/biomod2) -&gt; Popular
    package for ensemble modelling, but fixed on specific (non-Bayesian) engines and 
    no integration.
-   [sdmTMB](https://github.com/pbs-assess/sdmTMB) -&gt; Package for
    fitting spatial-Temporal SDMs.
-   [modleR](https://github.com/Model-R/modleR) -&gt; similar as biomod2
    and a wrapper to construct ensembles of models.
-   [kuenm](https://peerj.com/articles/6281/) -&gt; Another wrapper for
    Maxent.

Also in case the data allows to make robust inferences on the detectability of species occurrences, 
there is now also a new package available ([spOccupancy](https://www.jeffdoser.com/files/spoccupancy-web/)) that allows to fit spatial and integrated occupancy models in R.
