---
output:
  rmarkdown::github_document:
    html_preview: no
fontsize: 11pt
documentclass: article
---

```{r, include = FALSE}
devtools::load_all()
```

# Comparison with other SDM packages

Isn’t this just another SDM package? Indeed it is, but building our own
modelling infrastructure allows greater flexibility in how models are
created and run. It is less about reinventing the wheel, but rather
bringing strengths from different tools together. Furthermore the
_ibis.iSDM_ package puts particular emphasis on
*Non exhaustive list acknowledging other SDM packages in R:*

-   [hSDM](https://github.com/ghislainv/hSDM) -&gt; Bayesian framework
    for mixed models. Fast, but little flexibility with regards to
    weights or offsets
-   [multispeciesPP](https://github.com/wfithian/multispeciesPP) -&gt;
    Not been further developed since years
-   [inlabru](https://github.com/inlabru-org/inlabru) -&gt; Package
    specifically for LGCP with INLA, now integrated as engine in _ibis.iSDM_
-   [pointedSDMs](https://github.com/oharar/PointedSDMs) -&gt; INLA
    based SDM package for integrating different datasets.
-   [biomod2](https://github.com/biomodhub/biomod2) -&gt; Popular
    package for ensemble modeling, but no integration, not Bayesian
-   [sdmTMB](https://github.com/pbs-assess/sdmTMB) -&gt; Package for
    fitting spatial-Temporal SDMs
-   [modleR](https://github.com/Model-R/modleR) -&gt; similar as biomod2
    a wrapper to construct ensembles of models
-   [kuenm](https://peerj.com/articles/6281/) -&gt; Another wrapper for
    Maxent



