// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_kde2d
List cpp_kde2d(NumericVector x, NumericVector y, NumericVector h, IntegerVector n, NumericVector lims);
RcppExport SEXP _ibis_iSDM_cpp_kde2d(SEXP xSEXP, SEXP ySEXP, SEXP hSEXP, SEXP nSEXP, SEXP limsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lims(limsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kde2d(x, y, h, n, lims));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ibis_iSDM_cpp_kde2d", (DL_FUNC) &_ibis_iSDM_cpp_kde2d, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ibis_iSDM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
