# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Two-dimensional kernel density estimation
#'
#' Compute a bivariate Gaussian kernel density estimate.
#'
#' @param x Numeric vector of x coordinates.
#' @param y Numeric vector of y coordinates.
#' @param h Numeric vector of length 2 giving the bandwidths.
#' @param n Integer vector of length 2 giving the grid size.
#' @param lims Numeric vector of length 4 giving the limits
#'   \code{c(xmin, xmax, ymin, ymax)}.
#'
#' @return A list with components \code{x}, \code{y}, and \code{z}.
#'
#' @noRd
cpp_kde2d <- function(x, y, h, n, lims) {
    .Call(`_ibis_iSDM_cpp_kde2d`, x, y, h, n, lims)
}

