#' Logistic (invlogit) transformation function
#' @param x A [`numeric`] value.
#' @keywords utils
#' @noRd
logistic <- function(a){
  if(is.data.frame(a)){
    apply(a, 2, function(x) ilink(x, link = "logit") )
  } else {
    ilink(a, link = "logit")
  }
}

#' Logistic Richard curve
#' @description This function uses the five parameters logistic curve proposed
#' by Richards (1959) and suggested by Merow et al. (2017) as a way to weight
#' the expert knowledge. The equation associated to this logistic curve is
#'
#' \deqn{W(x) = u - \frac{u - l}{\left(1 + e^{-r(x-k)}\right)^{1/s}}}{W(x) = u -
#' (u - l)/((1 + exp(-r(x-k)))^(1/s))}. where eqn{u} and eqn{l} are the upper
#' and lower asymptotes of the logistic curve, eqn{r} is a rate that gives
#' flexibility to the curve from a sharpe step to a flat surface and eqn{s} is a
#' measure of skewness that adjust the symmetry of the decay on the edge of the
#' expert map. As for eqn{k}, it shifts the curve inside or outside the expert
#' map. Finally, eqn{x} is the provided vector.
#' @param x A [`numeric`] vector or any other input (e.g. [`SpatRaster`]) that
#'   can be used in the Richard's function.
#' @param lower A [`numeric`] of the lower asymptote.
#' @param upper A [`numeric`] of the upper asymptote.
#' @param rate A [`numeric`] of the rate.
#' @param skew A [`numeric`] of the skew.
#' @param shift A [`numeric`] of the shift.
#' @concept bossMaps
#' @references
#' * Richards, F. J. 1959. A flexible growth function for empirical use. \emph{Journal of Experimental Botany} \strong{10}:290–301
#' @aliases logisticRichard
#' @keywords utils
#' @noRd
logisticRichard <- function(x, lower = 1, upper = 1, rate = 1, skew = 1,
                            shift = 1) {
  # Check
  assertthat::assert_that(
    is.numeric(lower), is.numeric(upper),
    is.numeric(rate), is.numeric(skew),
    is.numeric(shift),
    skew > 0
  )

  # Fit curve
  y <- upper - ((upper - lower)/((1 + exp(-rate * (x - shift)))^(1/skew)))
  return(y)
}

#' Logit transformation function
#' @param x A [`numeric`] value.
#' @keywords utils
#' @noRd
logit <- function(a){
  if(is.data.frame(a)){
    apply(a, 2, function(x) log(x/(1-x))  )
  } else {
    log(a/(1-a))
  }
}

#' Inverse transformation function for the link function
#' @description back transforms a [numeric] vector using the appropriate link
#'   function
#' @param x A [`numeric`] vector generated by a model
#' @param link [`character`] indicating the link function to use (Default:
#'   \code{"log"}).
#' @aliases ilink
#' @examples
#'  ilink(rpois(10,.7), link = "log")
#'
#' @noRd
ilink <- function(x, link = "log"){
  assertthat::assert_that(is.numeric(x),
                          is.character(link)
  )
  link <- match.arg(link, c("identity", "log","logm1","log1p",
                            "inverse", "sqrt", "logit", "probit",
                            "cauchit", "cloglog") , several.ok = FALSE)
  switch (link,
          identity = x,
          log = exp(x),
          logm1 = exp(x) + 1,
          log1p = expm1(x),
          inverse = 1/x,
          sqrt = x^2,
          logit = ( 1 / (1 + exp(-x)) ),
          probit = stats::pnorm(x),
          cauchit = stats::pcauchy(x),
          cloglog = (1 - exp(-exp(x)))
  )
}

