# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: Pkgdown documentation

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install gdal and igraph dependencies on Linux (gdal)
        run: |
          sudo apt-get -y install \
          libudunits2-dev libgdal-dev libgeos-dev libproj-dev libglpk-dev

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: pkgdown
          extra-repositories: "https://inla.r-inla-download.org/R/testing"
          needs: website

      - name: Get remaining dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("urlchecker")

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'

      - name: Check URLs
        run: |
          result <- urlchecker::url_check()
          if (nrow(result) > 0) {
            print(result)
            stop("Invalid URLs detected")
          }
        shell: Rscript {0}
