# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check-linux

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release', pkgs: 'all'}
          - {os: ubuntu-20.04, r: 'devel', pkgs: 'all'}
          - {os: ubuntu-20.04, r: 'devel', pkgs: 'depends only'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_TIMINGS_: 10
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          extra-repositories: "https://inla.r-inla-download.org/R/testing"

      - name: Install gdal and igraph dependencies on Linux (gdal)
        run: |
          sudo apt-get -y install \
          libudunits2-dev libgdal-dev libgeos-dev libproj-dev libglpk-dev

     - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-repositories: "https://inla.r-inla-download.org/R/testing"
          extra-packages: |
             rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: Upload results if failed
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
